invenio/templates/application.yaml, invenio/templates/configuration.yaml, invenio/templates/services/logstash.yaml, invenio/templates/services/nginx.yaml, invenio/values.yaml
Co-authored-by: Diego Rodriguez <diego.rodriguez@cern.ch>
=> global: implementation of logstash

README.md, invenio/templates/application.yaml
Documented in https://github.com/inveniosoftware/docs-invenio-rdm/pull/41
Closes https://github.com/inveniosoftware/demo-inveniordm/issues/1
=> application: add inveno secret_key loading from secret

invenio/templates/configuration.yaml
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/782
=> conf: remove SITE_HOSTNAME

README.md, invenio/templates/deployments/worker.yaml, invenio/templates/pvc.yaml, invenio/values.yaml
Warning: I have not tested it! :)
=> celery: add beat deployment config

invenio/templates/deployments/rabbitmq.yaml
This PR is replacing the readiness probe for rabbitMq using the `rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms" command. This change is proposed after experiencing problems with the old command in our prod environment causing pods to restart forever while the rabbitMQ service was accessible from the terminal.
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license …
=> deployments: replace readiness probe with rabbitmq-diagnostics

invenio/templates/configurations/nginx.yaml
Nginx conf was missing this value [here](https://github.com/inveniosoftware/helm-invenio/blob/master/invenio/templates/configurations/nginx.yaml#L65)
=> nginx: fix missing value

invenio/templates/configurations/invenio.yaml
=> invenio: add community cache configuration

README.md, invenio/templates/configurations/invenio.yaml, invenio/templates/configurations/secrets.yaml, invenio/templates/deployments/web.yaml, invenio/templates/deployments/worker.yaml, invenio/values.yaml
* to review: https://gitlab.cern.ch/cds-team/cds-rdm-openshift/-/merge_requests/3
* to review https://gitlab.cern.ch/inveniosoftware/demo-inveniordm-openshift/-/merge_requests/5
* add volume mounts
* add extra environment variables
* add extra command for starting the containers
* add custom secrets
* change mounting path for celery pidfile
* update docs
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/56
=> invenio: add optional extra configuration

invenio/templates/configurations/flower.yaml
This change adds a missing `"`.
n/a
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s …
=> Fix typo in flower configuration

charts/invenio/templates/invenio-configmap.yaml, charts/invenio/values.yaml
This change replaces `'` with `"` in some places. These are the ones I've found. If you know of any other places, please point them out to me and I'll include them too in this PR if it makes sense.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
=> Replace `'` with `"`

charts/invenio/templates/flower/deployment.yaml, charts/invenio/templates/install-init-job.yaml, charts/invenio/templates/opensearch/deployment.yaml, charts/invenio/templates/postgresql/deployment.yaml, charts/invenio/templates/rabbitmq/deployment.yaml, charts/invenio/templates/redis/deployment.yaml, charts/invenio/templates/web-deployment.yaml, charts/invenio/templates/worker-deployment.yaml, charts/invenio/values.yaml
This change parameterizes the timezone variable used across deployments. The new value is `global.timezone`, following [Bitnamis pattern](https://github.com/bitnami/charts/tree/main/bitnami/apache) of having a `globals` object for values that are used across multiple components.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6- …
=> Parameterize timezone variable

charts/invenio/templates/_helpers.tpl, charts/invenio/templates/ingress.yaml, charts/invenio/values.yaml
This change rewrites major parts of the Ingress resource to bring it up-to-date with the current Ingress API specifications, along with some other improvements. This includes:
* Ability to set custom annotations.
* Dynamic creation of TLS secret name.
* Remove support for `networking.k8s.io/v1beta1`.
Please see each commit for further details.
**Reminder**
2. You agree that you have the right to license your contribution under …
=> ingress: Rewrite Ingress resource

charts/invenio/values.yaml
This reverts commit f507397fbb75e3d95d8338959e61542c1c97e633.
Please see discussion here: https://github.com/inveniosoftware/helm-invenio/pull/105#discussion_r1532791215
**Reminder**
1. You license your contribution under the same terms …
=> Revert "opensearch: Disable sysctlImage privileged container"

charts/invenio/templates/flower/secret.yaml
All other Flower components has logic that disables creation of the objects if `flower.enabled` is not true. This change adds that logic to Flower's Secret too.
**Reminder**
1. You license your contribution under the same terms as the …
=> flower: toggle secret via flower.enabled

charts/invenio/templates/persistentvolumeclaim.yaml, charts/invenio/values.yaml
This change adds the option to set custom annotations for the shared-volume PVC.
**Frontend**
**Reminder**
2. You agree that you have the right to license your …
=> Enable custom annotations for shared-volume PVC

charts/invenio/templates/flower/deployment.yaml, charts/invenio/templates/web-deployment.yaml, charts/invenio/templates/worker-beat-deployment.yaml, charts/invenio/templates/worker-deployment.yaml, charts/invenio/values.yaml
> Please describe briefly your pull request.
In OpenShift, where the user ID (UID) and group ID (GID) are automatically managed, the ability to remove these settings from the pod security context simplifies deployment
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repos …
=> invenio: Add option to enable/disable podSecurityContext

charts/invenio/Chart.lock, charts/invenio/Chart.yaml
This change upgrades the OpenSearch dependency to chart version 1.4.0 (OpenSearch version 2.18.0).
**Frontend**
**Reminder**
2. You agree that you have the right …
=> Update bitnami/opensearch to 1.4.0

.github/workflows/release.yml, charts/invenio/Chart.yaml
=> chore: add chart releaser action and increase version

charts/invenio/Chart.yaml, charts/invenio/templates/invenio-configmap.yaml
Before this change, `INVENIO_IIIF_CACHE_REDIS_URL` was unset and defaulted to `redis://localhost:6379/0`:
```console
$ invenio shell --no-term-title -c "from flask import current_app; print(current_app.config.get(\"IIIF_CACHE_REDIS_URL\"))"'
redis://localhost:6379/0
```
https://github.com/inveniosoftware/flask-iiif/blob/f5b8928de88a72ea455c79872d041add1db84e92/flask_iiif/config.py#L75
This change fixes that by setting it dynamically in the chart.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/membe …
=> Set `INVENIO_IIIF_CACHE_REDIS_URL`

charts/invenio/templates/install-init-job.yaml, charts/invenio/templates/vocabularies-configmap.yaml, charts/invenio/templates/web-deployment.yaml, charts/invenio/templates/worker-beat-deployment.yaml, charts/invenio/templates/worker-deployment.yaml, charts/invenio/values.yaml
* Adds the option to customize vocabularies (closes #135)
* Adds proper labels everywhere
=> Enable custom vocabularies via ConfigMaps

charts/invenio/Chart.yaml
This change bumps chart version to 0.5.0, tagging it will publish a new release. I think workflows triggers on all tags, not just tags on master, so I have not tagged this yet.
**Frontend**
**Reminder**
1. You license your contribution under the same …
=> chore: Bump chart version to 0.5.0

charts/invenio/templates/ingress.yaml
This change fixes a typo for service name in the Ingress resource.
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution …
=> fix: Use correct service name in Ingress

charts/invenio/Chart.yaml
Bump chart version to 0.5.1.
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.
=> 📦 release: v0.5.1

charts/invenio/templates/secret.yaml
This change fixes a bug where the secret was generated even if existing secret was provided.
**Frontend**
**Reminder**
2. …
=> fix: Reverse logic for creating invenio secret

charts/invenio/templates/web-deployment.yaml, charts/invenio/templates/worker-beat-deployment.yaml, charts/invenio/templates/worker-deployment.yaml, charts/invenio/values.yaml
This changes makes it possible to configure the security context for all containers and initContainers in the web, worker and worker-beat pods.
**Frontend**
**Reminder**
1. You license your contribution under the …
=> feat: Parameterize securityContext for web, worker and worker-beat

charts/invenio/templates/worker-beat-deployment.yaml
Fix a typo in the worker-beat Deployment, where the container was assigned the podSecurityContext instead of securityContext.
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the …
=> fix: podSecurityContext --> securityContext in beat

charts/invenio/Chart.yaml
Release  v0.5.3
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.
=> 📦 release: v0.5.3

charts/invenio/templates/uwsgi-configmap.yaml, charts/invenio/values.yaml
> Please describe briefly your pull request.
**Frontend**
**Reminder**
2. You agree that you have the right to license …
=> Extra config uwsgi

charts/invenio/Chart.lock, charts/invenio/Chart.yaml
This is the latest version of the Bitnami chart without changing major version.
Importantly, this version lets us set resource requests for the backup cronjob.
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the …
=> chore: Upgrade bitnami/postgresql to 14.3.3

charts/invenio/templates/secret.yaml
* Helm will update randomly generated secrets on every release update.
=> secret: preserve previously generated secret

charts/invenio/templates/flower/deployment.yaml, charts/invenio/templates/web-deployment.yaml, charts/invenio/templates/worker-beat-deployment.yaml, charts/invenio/templates/worker-deployment.yaml, charts/invenio/values.yaml
This feature allows users to specify a list of `secretRef` or `configMapRef` objects which should be added to the `envFrom` field in the Invenio containers. This reduces the need for repeating the name and value of each environment variable that the user wants to add; instead they can simply define them all in one or more secrets/configmaps and let `envFrom` do the work of adding each variable to the container's environment.
**Frontend**
**Reminder**
By using GitHub, …
=> feat: Add extraEnvFrom for mounting multiple secrets/cms

charts/invenio/templates/flower/deployment.yaml, charts/invenio/templates/web-deployment.yaml, charts/invenio/templates/worker-beat-deployment.yaml, charts/invenio/templates/worker-deployment.yaml, charts/invenio/values.yaml
This PR makes it possible to configure `livenessProbe`, `readinessProbe` and `startupProbe` for all Invenio components.
Fixes #110 
**Frontend**
**Reminder**
2. You agree that you have the …
=> feat: Introduce configurable health probes

charts/invenio/values.yaml
This change fixes a typo that broke the web container's `readinessProbe`.
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current …
=> fix: correct a typo in the web readinessProbe

charts/invenio/Chart.yaml
This change triggers the release of v0.6.0, once it's merged and tagged.
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current …
=> 📦 release: v0.6.0

charts/invenio/Chart.yaml
Merge after https://github.com/inveniosoftware/helm-invenio/pull/186
=> 📦 release: v0.7.0

charts/invenio/templates/web-deployment.yaml, charts/invenio/values.yaml
> Please describe briefly your pull request.
add ability to create Volumes in web pod i need this do add a custom CA certificate
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the current repository’s …
=> feat(Web): add ability to create Volumes in web pod

README.md
The `web.image` and `worker.image` have been deprecated. Here’s an update to the README to reflect this. Other parts of the documentation may need to be updated, but this is what I’ve noticed so far.
**Frontend**
**Reminder**
1. You license your contribution under the same terms …
=> doc: update image values configuration in README

charts/invenio/templates/route.yaml, charts/invenio/values.yaml
Using `.Values.main_route.annotations` is meant to set annotations on the Route. However, it didn’t seem to work properly before. I may have missed something, but I believe it’s also worth aligning the templating with the syntax used on the Ingress object.
I’ve also added an empty default value in `values.yaml` as well as rudimentary documentation.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
=> fix: route annotations
