- invenio/templates/application.yaml
- invenio/templates/configuration.yaml
- invenio/templates/services/nginx.yaml
- invenio/templates/volumes.yaml
- invenio/values.yaml
Now Nginx and Web nodes share a volume (Persistent) for statics. However, it needs the image to have the statics (Addresse here https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/56).
Since volumes override the folder where they are being mounted (empty them). The web pod folder is "wiped out" of statics. To solve the issue an `initContainer` is launched, this will mount the volume in a temporary location and copy the statics to it. Therefore, it will be initialized with the correct statics. The copy of those is made to overwrite old ones, so there is no problem with future deployments.
The serving of statics has been off-loaded to nginx. Deeper consolidations are out of the scope of this PR, but will be addressed as part of …
> web/nginx: shared volume (pvc - persistent volume claim)

- .gitignore
- invenio-k8s/templates/_helpers.tpl
- invenio-k8s/templates/application.yaml
- invenio-k8s/templates/configuration.yaml
- invenio-k8s/templates/secrets.yaml
- invenio-k8s/templates/services/elasticsearch.yaml
- invenio-k8s/templates/services/postgresql.yaml
- invenio-k8s/templates/services/rabbitmq.yaml
- invenio-k8s/values.yaml
I added the ability to use existing secrets to the vanilla kubernetes chart. The redis hostname is now configurable as well to make it possible to use a self-managed deployment. The possibility to define the max upload size was addded, too.
> Make already existing secrets usable

- README.md
- benchmark/locustfile.py
- invenio/templates/configurations/invenio.yaml
- invenio/templates/configurations/secrets.yaml
- invenio/templates/deployments/rabbitmq.yaml
- invenio/templates/deployments/web.yaml
- invenio/templates/deployments/worker.yaml
- invenio/values.yaml
Add support for:
- Sentry
- Remote app auth. Zenodo is planning on setting ORCiD, GitHub and AAI.
Fixes some minor configuration issues with secrets, workers and rabbitmq.
When merged open tickets to add support for:
- Kibana
- Flower
- PGadmin
- Sentry
> global: add sentry and remote applications support

- invenio/templates/configurations/nginx.yaml
closes https://github.com/inveniosoftware/helm-invenio/issues/47
Notes:
- file `robots.txt` was [added](https://github.com/inveniosoftware/invenio-app-rdm/commit/cb5bd39104c8a40ef98a18b3b7c42d7da877e08d) in `invenio-app-rdm` and will only be available for images whose version of `invenio-app-rdm` were upgraded.
> nginx: added robots.txt rule

- invenio/templates/configurations/invenio.yaml
closes https://github.com/inveniosoftware/helm-invenio/issues/53
This is just a workaround - since invenio is evaluating the environment variables as Python literals, those should NOT used as YAML guard variables in the helm charts, or every "false" value will be evaluated to true leading to misconfigurations
> Explicitly set boolean values with their python literals

- invenio/templates/deployments/worker.yaml
`-d` is used to check for worker node names, but now beat has no worker
> celery beat: remove worker need from liveness probe

- README.md
- invenio/templates/configurations/invenio.yaml
- invenio/templates/configurations/secrets.yaml
- invenio/templates/deployments/web.yaml
- invenio/templates/deployments/worker.yaml
- invenio/values.yaml
- closes https://github.com/zenodo/zenodo-rdm/issues/113
- example: https://gitlab.cern.ch/zenodo/zenodo-rdm-openshift/-/merge_requests/1
Helm Charts do not accept injecting external files, as a security feature. We could still have the values in different files, but given that the way of injecting them would be the same we might as well just have one `values.yaml` file.
> configurations: support invenio config injection

- invenio/templates/deployments/rabbitmq.yaml
- invenio/templates/deployments/redis.yaml
- invenio/values.yaml
closes https://github.com/zenodo/zenodo-rdm/issues/524
Redis and MQ resources were not configurable, on Zenodo-RDM we have to be able to tweak them on deployment.
> deployments: added resources to redis and mq.

- invenio/templates/configurations/logstash.yaml
The recent version of logstash changes the names of the geo location field. This rename is to make it compatible with the legacy system
> logstash: recent version of logstash changes the name of the geo field

- charts/invenio/templates/flower/deployment.yaml
- charts/invenio/templates/web-deployment.yaml
- charts/invenio/templates/worker-beat-deployment.yaml
- charts/invenio/templates/worker-deployment.yaml
- charts/invenio/values.yaml
This change makes the `worker-beat` pod compliant with the Pod Security Standard "restricted". For more information, please see: <https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted>
There are still a handful of policy violations left:
```
W0212 13:13:00.741679    8975 warnings.go:70] would violate PodSecurity "restricted:latest": privileged (container "sysctl" must not set securityContext.privileged=true), allowPrivilegeEscalation != false (container "sysctl" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "sysctl" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "sysctl" must set securityContext.runAsNonRoot=true), runAsUser=0 (container "sysctl" must not set …
```
> Set securityContext for compliance with PSS "restricted"

- charts/invenio/templates/web-deployment.yaml
The web container used a subPath for the mountPaths while the worker container did not.
This caused issues where files were uploaded but could not be found by the worker.
This change fixes that by removing the redundant subPath.
Before: /opt/invenio/var/instance/data/data/
After: /opt/invenio/var/instance/data/
Please describe briefly your pull request.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s …
> web: remove redundant subpath for volumemounts

- charts/invenio/templates/persistentvolumeclaim.yaml
Without the additional logic introduced in this change, the `storageClassName` field would by default be set to empty string.
For systems with a default storage class configured, setting `storageClassName` to the empty string would be OK during installation since the storage class controller will set the `storageClassName` afterwards.
This, however, does not work for upgrades because then the `storageClassName` of the live object is already set to something and then we try to change that immutable field to the empty string.
This change ensures that the `storageClassName` is only set if we specify `persistence.storage_class`.
If you've added [third-party code (copy/pasted or new …
> persistence: avoid setting empty storageClassName

- charts/invenio/values.yaml
This change fixes a typo for the default value (and importantly: type) of the `invenio.extra_env_from_secret` value.
Before this change, I got the following warning when setting `invenio.extra_env_from_secret`:
```text
coalesce.go:286: warning: cannot overwrite table with non table for invenio.invenio.extra_env_from_secret (map[])
```
This was because the default value of `invenio.extra_env_from_secret` was `{}` (the empty object) while it is clearly used as a list:
https://github.com/inveniosoftware/helm-invenio/blob/eb6544fdeb7e762972db1dae26f848c2f2e4c029/charts/invenio/templates/web-deployment.yaml#L83-L89
https://github.com/inveniosoftware/helm-invenio/blob/eb6544fdeb7e762972db1dae26f848c2f2e4c029/charts/invenio/templates/worker-deployment.yaml#L87-L93
So when setting …
> Change type of `invenio.extra_env_from_secret`

- charts/invenio/templates/NOTES.txt
- charts/invenio/templates/invenio-configmap.yaml
- charts/invenio/values.yaml
The first commit is the one that contains the change. 
The second one is a "test" to see what you think about renaming all the non-camelcase variables we have and deprecating them.
> Templated variables inside invenio-config configMap

- charts/invenio/templates/invenio-configmap.yaml
This change replaces the deprecated `RATELIMIT_STORAGE_URL` with `RATELIMIT_STORAGE_URI`.
Deprecation can be found here: https://github.com/inveniosoftware/invenio-app/blob/b904bb7319d179b8c32bb0b60660f786319b5b8c/invenio_app/ext.py#L113-L119
Fixes #139
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
> Change RATELIMIT_STORAGE_URL to RATELIMIT_STORAGE_URI

- charts/invenio/templates/NOTES.txt
- charts/invenio/templates/_helpers.tpl
- charts/invenio/templates/install-init-job.yaml
- charts/invenio/templates/sentry-secret.yaml
- charts/invenio/templates/web-deployment.yaml
- charts/invenio/templates/worker-beat-deployment.yaml
- charts/invenio/templates/worker-deployment.yaml
- charts/invenio/values.yaml
invenio: refactor sentry block
* Deprecates non-camelcase sentry variables.
* Addresses secret handling as described in #117.
> refactor sentry section 

- charts/invenio/templates/_helpers.tpl
- charts/invenio/templates/invenio-configmap.yaml
---
Without any extra variable or overwrite
```
invenio:
hostname: foo
secret_key: foo
security_login_salt: foo
csrf_secret_salt: foo
postgresql:
auth:
password: foo
rabbitmq:
enabled: true
auth:
password: foo
```
```
$ helm template -f values.yaml  ./charts/invenio  -s templates/invenio-configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
name: invenio-config
labels:
helm.sh/chart: invenio-0.3.0
app.kubernetes.io/name: invenio
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "v12.0.0-beta.1.3"
app.kubernetes.io/managed-by: Helm
data:
INVENIO_ACCOUNTS_SESSION_REDIS_URL: redis://release-name-redis-master:6379/1
INVENIO_APP_ALLOWED_HOSTS: '["foo"]'
INVENIO_CACHE_REDIS_HOST: release-name-redis-master
INVENIO_CACHE_REDIS_URL: redis://release-name-redis-master:6379/0 …
```
> invenio: merge base config and extraConfig

- charts/invenio/templates/NOTES.txt
- charts/invenio/templates/_helpers.tpl
- charts/invenio/templates/install-init-job.yaml
- charts/invenio/templates/secret.yaml
- charts/invenio/templates/web-deployment.yaml
- charts/invenio/templates/worker-beat-deployment.yaml
- charts/invenio/templates/worker-deployment.yaml
- charts/invenio/values.yaml
* Adds missing salts to harden security.
* Deprecates plain keys and forces to use secrets for them.
* Automatically generates secret key and salts if no secret is provided.
> invenio: better secret key and salts management

- charts/invenio/templates/install-init-job.yaml
- charts/invenio/templates/web-deployment.yaml
- charts/invenio/templates/worker-beat-deployment.yaml
- charts/invenio/templates/worker-deployment.yaml
The `envFrom` field takes `secretRef`, not
`secretKeyRef` like `env.valueFrom` does.
**Frontend**
**Reminder**
2. You agree that you have the right to license …
> fix: change secretKeyRef to secretRef in envFrom

- charts/invenio/templates/worker-beat-deployment.yaml
Before this change, worker-beat had the default strategy "RollingUpdate", allowing for two replicas to temporarily coexist during updates.
This, however, was not safe behavior for worker-beat, as documented here: https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html
> You have to ensure only a single scheduler is running for a schedule
> at a time, otherwise you’d end up with duplicate tasks. Using a
> centralized approach means the schedule doesn’t have to be
> synchronized, and the service can operate without using locks.
This change fixes this by setting the "Recreate" strategy, ensuring that more than 1 replica never exists.
* If you have added [third-party code (copy/pasted or new …
> fix: Set Recreate strategy in beat for safety

- charts/invenio/templates/NOTES.txt
- charts/invenio/templates/_helpers.tpl
- charts/invenio/templates/datacite-secret.yaml
- charts/invenio/templates/web-deployment.yaml
- charts/invenio/templates/worker-beat-deployment.yaml
- charts/invenio/templates/worker-deployment.yaml
- charts/invenio/values.yaml
* Deprecates non-camelcase datacite variables.
* Addresses secret handling as described in #117.
> invenio: refactor datacite block

- charts/invenio/templates/NOTES.txt
- charts/invenio/templates/flower/deployment.yaml
- charts/invenio/templates/haproxy/deployment.yaml
- charts/invenio/templates/web-deployment.yaml
- charts/invenio/templates/worker-beat-deployment.yaml
- charts/invenio/templates/worker-deployment.yaml
- charts/invenio/values.yaml
This PR normalizes how we set `resources` for each container and initContainer, first by standardizing how we include the values in the templates and secondly by resouces to `{}` by default, aligned with Bitnami's standard.
Here's one example of Bitnami documenting their reasoning for it:
> We usually recommend not to specify default resources and to leave this as a conscious choice for the user. This also increases chances charts run on environments with little resources, such as Minikube.
— https://github.com/bitnami/charts/blob/7345c0bb2842b73f299aacd2af37147bd7b714cd/bitnami/nginx/values.yaml#L331-L334
We don't have to follow Bitnami's standard, but I think it's reasonable to do so. Unless we are very confident that a container has some upper/lower bound on its resource utilization, …
> chore: Normalize how `resources` are set for each container

- charts/invenio/Chart.yaml
- charts/invenio/templates/NOTES.txt
- charts/invenio/templates/_helpers.tpl
- charts/invenio/templates/install-init-job.yaml
- charts/invenio/templates/web-deployment.yaml
- charts/invenio/templates/worker-beat-deployment.yaml
- charts/invenio/templates/worker-deployment.yaml
- charts/invenio/values.yaml
> values: refactor image block

- charts/invenio/Chart.yaml
- charts/invenio/values.yaml
- Use `12.0.10` instead of `v12.0.10` in `appVersion`, so it's compliant with the tag of the default image.
- Fix typo ghrc.io --> ghcr.io
- Fix typo where image name was part of the tag.
- DRY: Unset the `tag` value, so we default to using `appVersion`.
- Unset deprecated image fields.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-rep …
> fix: Use correct default image values

- charts/invenio/values.yaml
When `.Values.image.imagePullSecrets` was introduced in #174, we opted to use the same format for `imagePullSecrets` list as used in Kubernetes' PodSpec; it's a list of objects that requires each list element to have the key `name`.
We failed to indicate this in the example given in the comment. This change fixes that.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
> fix: Include `name` key in example of imagePullSecrets

- charts/invenio/values.yaml
This change unsets the deprecated `invenio.datacite.secret_name` value, which has been repaced by `invenio.datacite.existingSecret`, so that the deprecation warning only shows up if a user has explicitly set the deprecated value.
**Frontend**
**Reminder**
1. You license your …
> chore: Set datacite secret using new parameter

- charts/invenio/templates/NOTES.txt
This change improves the logic for when the warning about missing resources should be printed.
Before, it printed even for disabled resources.
Now, it does not print a warning for disabled resources and it dynamically checks for `initContainers` subresources.
Fixes #182
> [!TIP]
> This change is easier to review if you ignore space changes.
> 
> `git show --ignore-space-change`
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms …
> fix: Improve missing resources warning

- charts/invenio/templates/flower/deployment.yaml
- charts/invenio/templates/web-deployment.yaml
- charts/invenio/templates/worker-beat-deployment.yaml
- charts/invenio/templates/worker-deployment.yaml
- charts/invenio/values.yaml
Flower has nothing to do with Invenio. Adding the `invenio.extraEnvFrom` is unnecessary and can potentially cause some leakage.
> values: allow templates values in extraEnvFrom

- README-Kubernetes.md
> Please describe briefly your pull request.
The name of this property was changed in 97fd16598e02765d1dfb01baa1eb96c33e361891  but the Kubernetes doc was not updated to match.
**Reminder**
1. You license your contribution under the same …
> docs: sslSecretName -> tlsSecretNameOverride in k8s docs

- charts/invenio/templates/web-deployment.yaml
- charts/invenio/templates/worker-beat-deployment.yaml
- charts/invenio/templates/worker-deployment.yaml
When using pod annotations or labels, rendering of the chart fails with
```
Helm Error: template: (...) executing "invenio/charts/invenio/templates/(...)" at <tpl>: wrong number of args for tpl: want 2 got 1
```
due to a missing context parameter.
Btw, below links from the PR template are outdated ;)
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-re …
> Fix pod annotation/label templates
